const STATIC_MODULE_FLAGS = {
  authentication: true,
  permissions: true,
  role_permission_setup: true,
  module_settings: true,
  user_management: true,
  dashboard: true,
  dashboard_analytics: true,
  overview_1: true,
  overview_2: true,
  dashboard_summary: true,
  employee: true,
  employee_master: true,
  own_profile: true,
  masters: true,
  company_master: true,
  site_master: true,
  department_master: true,
  sub_department_master: true,
  designation_master: true,
  checklist: true,
  checklist_master: true,
  tasks: true,
  your_checklist: true,
  assigned_checklists: true,
  checklist_transfer: true,
  approval_inbox: true,
  own_task: true,
  shared_task: true,
  attendance: true,
  employee_attendance: true,
  attendance_reports: true,
  attendance_regularization: true,
  attendance_settings: true,
  polling: false,
  assigned_polls: true,
  poll_results: true,
  poll_report: true,
  complaints: false,
  complaint_dashboard: true,
  complaint_report: true,
  chat: true,
  site_chat: true,
  department_chat: true,
  notifications: true,
  feedback: true,
  reports: true,
  checklist_report: true,
  checklist_task_report: true,
  workflow: true,
  workflow_mapping: true,
  approval_hierarchy: true,
  admin: true,
  admin_approvals: true,
  settings_masters: true,
};

const MODULE_SETTINGS_CATALOG = [
  {
    moduleKey: "authentication",
    moduleName: "Authentication",
    parentGroup: "System",
    isSystemRequired: true,
    description: "Login, token validation, and account session handling.",
    sortOrder: 1,
  },
  {
    moduleKey: "permissions",
    moduleName: "Permissions",
    parentGroup: "System",
    isSystemRequired: true,
    description: "Core permission resolver and access checks.",
    sortOrder: 2,
  },
  {
    moduleKey: "dashboard",
    moduleName: "Dashboard",
    parentGroup: "Dashboard",
    isSystemRequired: true,
    description: "Role-based landing dashboard and workspace shortcuts.",
    sortOrder: 10,
  },
  {
    moduleKey: "dashboard_analytics",
    moduleName: "Dashboard Analytics",
    parentGroup: "Dashboard",
    description: "Overview dashboards, drilldowns, and summary analytics.",
    sortOrder: 20,
  },
  {
    moduleKey: "overview_1",
    moduleName: "Overview 1",
    parentGroup: "Dashboard",
    description: "Company and site overview dashboard.",
    sortOrder: 21,
  },
  {
    moduleKey: "overview_2",
    moduleName: "Overview 2",
    parentGroup: "Dashboard",
    description: "Workflow hierarchy overview dashboard.",
    sortOrder: 22,
  },
  {
    moduleKey: "dashboard_summary",
    moduleName: "Summary",
    parentGroup: "Dashboard",
    description: "Dashboard marks summary screen.",
    sortOrder: 23,
  },
  {
    moduleKey: "employee_master",
    moduleName: "Employee Master",
    parentGroup: "Workspace",
    description: "Employee directory, profiles, onboarding, and activation controls.",
    sortOrder: 30,
  },
  {
    moduleKey: "own_profile",
    moduleName: "Own Profile",
    parentGroup: "Workspace",
    description: "Current user profile screen.",
    sortOrder: 40,
  },
  {
    moduleKey: "masters",
    moduleName: "Masters",
    parentGroup: "Masters",
    description: "Master data group switch.",
    sortOrder: 45,
  },
  {
    moduleKey: "company_master",
    moduleName: "Company Master",
    parentGroup: "Masters",
    description: "Company and director master data.",
    sortOrder: 50,
  },
  {
    moduleKey: "site_master",
    moduleName: "Site Master",
    parentGroup: "Masters",
    description: "Site and sub-site master data.",
    sortOrder: 60,
  },
  {
    moduleKey: "department_master",
    moduleName: "Department Master",
    parentGroup: "Masters",
    description: "Department and leadership mapping.",
    sortOrder: 70,
  },
  {
    moduleKey: "sub_department_master",
    moduleName: "Sub Department Master",
    parentGroup: "Masters",
    description: "Nested sub-department setup inside departments.",
    sortOrder: 80,
  },
  {
    moduleKey: "designation_master",
    moduleName: "Designation Master",
    parentGroup: "Masters",
    description: "Designation and role title master setup.",
    sortOrder: 90,
  },
  {
    moduleKey: "checklist",
    moduleName: "Checklist",
    parentGroup: "Checklist",
    isSystemRequired: true,
    description: "Checklist operations group switch.",
    sortOrder: 95,
  },
  {
    moduleKey: "checklist_master",
    moduleName: "Checklist Master",
    parentGroup: "Checklist",
    description: "Checklist definitions and schedule setup.",
    sortOrder: 100,
  },
  {
    moduleKey: "tasks",
    moduleName: "Tasks",
    parentGroup: "Checklist",
    description: "Checklist task list and admin task view.",
    sortOrder: 110,
  },
  {
    moduleKey: "your_checklist",
    moduleName: "Your Checklist",
    parentGroup: "Checklist",
    description: "Personal checklist task workspace.",
    sortOrder: 111,
  },
  {
    moduleKey: "assigned_checklists",
    moduleName: "Assigned Checklist",
    parentGroup: "Checklist",
    description: "Assigned checklist task access.",
    sortOrder: 112,
  },
  {
    moduleKey: "checklist_transfer",
    moduleName: "Checklist Transfer",
    parentGroup: "Masters",
    description: "Checklist reassignment tools.",
    sortOrder: 120,
  },
  {
    moduleKey: "approval_inbox",
    moduleName: "Approval Inbox",
    parentGroup: "Checklist",
    description: "Pending approvals and checklist action inbox.",
    sortOrder: 130,
  },
  {
    moduleKey: "own_task",
    moduleName: "Own Task",
    parentGroup: "Workspace",
    description: "Personal reminder and task workspace.",
    sortOrder: 140,
  },
  {
    moduleKey: "shared_task",
    moduleName: "Shared Task",
    parentGroup: "Workspace",
    description: "Shared task collaboration shell.",
    sortOrder: 150,
  },
  {
    moduleKey: "attendance",
    moduleName: "Attendance",
    parentGroup: "Attendance",
    description: "Attendance module group switch.",
    sortOrder: 160,
  },
  {
    moduleKey: "employee_attendance",
    moduleName: "Employee Attendance",
    parentGroup: "Attendance",
    description: "Attendance dashboard, daily entry, and self attendance.",
    sortOrder: 170,
  },
  {
    moduleKey: "attendance_reports",
    moduleName: "Attendance Reports",
    parentGroup: "Attendance",
    description: "Attendance summaries and exports.",
    sortOrder: 180,
  },
  {
    moduleKey: "attendance_regularization",
    moduleName: "Attendance Regularization",
    parentGroup: "Attendance",
    description: "Attendance correction requests and approvals.",
    sortOrder: 190,
  },
  {
    moduleKey: "attendance_settings",
    moduleName: "Attendance Settings",
    parentGroup: "Attendance",
    description: "Attendance timing and self-service rules.",
    sortOrder: 200,
  },
  {
    moduleKey: "polling",
    moduleName: "Polling System",
    parentGroup: "Workspace",
    description: "Poll creation, assignment, response, and reporting group switch.",
    sortOrder: 210,
  },
  {
    moduleKey: "assigned_polls",
    moduleName: "Assigned Polls",
    parentGroup: "Workspace",
    description: "Employee assigned poll inbox.",
    sortOrder: 220,
  },
  {
    moduleKey: "poll_results",
    moduleName: "Poll Results",
    parentGroup: "Reports",
    description: "Aggregated poll results screen.",
    sortOrder: 230,
  },
  {
    moduleKey: "poll_report",
    moduleName: "Poll Report",
    parentGroup: "Reports",
    description: "Poll report access and exports.",
    sortOrder: 240,
  },
  {
    moduleKey: "complaints",
    moduleName: "Complaints",
    parentGroup: "Workspace",
    description: "Complaint submission, workflow, notification, and reporting group switch.",
    sortOrder: 250,
  },
  {
    moduleKey: "complaint_dashboard",
    moduleName: "Complaint Dashboard",
    parentGroup: "Workspace",
    description: "Complaint dashboard cards and work queue.",
    sortOrder: 260,
  },
  {
    moduleKey: "complaint_report",
    moduleName: "Complaint Report",
    parentGroup: "Reports",
    description: "Complaint report filters and exports.",
    sortOrder: 270,
  },
  {
    moduleKey: "chat",
    moduleName: "Chat",
    parentGroup: "Communication",
    description: "Communication group switch.",
    sortOrder: 280,
  },
  {
    moduleKey: "site_chat",
    moduleName: "Site Chat",
    parentGroup: "Communication",
    description: "Site-wide conversation channel.",
    sortOrder: 290,
  },
  {
    moduleKey: "department_chat",
    moduleName: "Department Chat",
    parentGroup: "Communication",
    description: "Department-level conversation channel.",
    sortOrder: 300,
  },
  {
    moduleKey: "notifications",
    moduleName: "Notifications",
    parentGroup: "Communication",
    description: "Notification center and alert visibility.",
    sortOrder: 310,
  },
  {
    moduleKey: "feedback",
    moduleName: "Feedback",
    parentGroup: "Communication",
    description: "Employee feedback notifications and review.",
    sortOrder: 320,
  },
  {
    moduleKey: "reports",
    moduleName: "Reports",
    parentGroup: "Reports",
    description: "Reports group switch.",
    sortOrder: 330,
  },
  {
    moduleKey: "checklist_report",
    moduleName: "Checklist Report",
    parentGroup: "Reports",
    description: "Checklist report screen and export.",
    sortOrder: 340,
  },
  {
    moduleKey: "checklist_task_report",
    moduleName: "Checklist Task Report",
    parentGroup: "Reports",
    description: "Checklist task report and mark split-up.",
    sortOrder: 350,
  },
  {
    moduleKey: "workflow",
    moduleName: "Workflow",
    parentGroup: "Workflow",
    description: "Workflow module group switch.",
    sortOrder: 360,
  },
  {
    moduleKey: "workflow_mapping",
    moduleName: "Workflow Mapping",
    parentGroup: "Workflow",
    description: "Workflow mapping setup.",
    sortOrder: 370,
  },
  {
    moduleKey: "approval_hierarchy",
    moduleName: "Approval Hierarchy",
    parentGroup: "Workflow",
    description: "Approval hierarchy setup.",
    sortOrder: 380,
  },
  {
    moduleKey: "user_management",
    moduleName: "User Management",
    parentGroup: "Admin",
    isSystemRequired: true,
    description: "Login-user administration.",
    sortOrder: 390,
  },
  {
    moduleKey: "role_permission_setup",
    moduleName: "Role Permission Setup",
    parentGroup: "Admin",
    isSystemRequired: true,
    description: "Role matrix, overrides, and mapping administration.",
    sortOrder: 400,
  },
  {
    moduleKey: "module_settings",
    moduleName: "Module Settings",
    parentGroup: "Admin",
    isSystemRequired: true,
    description: "Enable or disable completed modules safely.",
    sortOrder: 410,
  },
  {
    moduleKey: "admin_approvals",
    moduleName: "Admin Approvals",
    parentGroup: "Admin",
    description: "Checklist master admin approval queue.",
    sortOrder: 420,
  },
  {
    moduleKey: "settings_masters",
    moduleName: "Settings",
    parentGroup: "Admin",
    description: "General settings and master shell.",
    sortOrder: 430,
  },
];

const MODULE_DEPENDENCIES = {
  authentication: ["authentication"],
  permissions: ["permissions"],
  role_permission_setup: ["permissions", "role_permission_setup"],
  module_settings: ["permissions", "module_settings"],
  user_management: ["permissions", "user_management"],
  dashboard: ["dashboard"],
  dashboard_analytics: ["dashboard", "dashboard_analytics"],
  overview_1: ["dashboard", "dashboard_analytics", "overview_1"],
  overview_2: ["dashboard", "dashboard_analytics", "overview_2"],
  dashboard_summary: ["dashboard", "dashboard_analytics", "dashboard_summary"],
  employee_master: ["employee_master"],
  own_profile: ["own_profile"],
  company_master: ["masters", "company_master"],
  site_master: ["masters", "site_master"],
  department_master: ["masters", "department_master"],
  sub_department_master: ["masters", "department_master", "sub_department_master"],
  designation_master: ["masters", "designation_master"],
  checklist: ["checklist"],
  checklist_master: ["checklist", "checklist_master"],
  tasks: ["checklist", "tasks"],
  your_checklist: ["checklist", "your_checklist", "assigned_checklists"],
  assigned_checklists: ["checklist", "assigned_checklists"],
  checklist_transfer: ["checklist", "checklist_transfer"],
  approval_inbox: ["checklist", "approval_inbox"],
  own_task: ["checklist", "own_task"],
  shared_task: ["checklist", "shared_task"],
  admin_approvals: ["checklist", "admin_approvals"],
  attendance: ["attendance"],
  employee_attendance: ["attendance", "employee_attendance"],
  attendance_reports: ["attendance", "attendance_reports"],
  attendance_regularization: ["attendance", "attendance_regularization"],
  attendance_settings: ["attendance", "attendance_settings"],
  polling: ["polling"],
  poll_master: ["polling"],
  assigned_polls: ["polling", "assigned_polls"],
  poll_results: ["polling", "poll_results"],
  poll_report: ["polling", "poll_report"],
  complaints: ["complaints"],
  complaint_dashboard: ["complaints", "complaint_dashboard"],
  complaint_report: ["complaints", "complaint_report"],
  chat: ["chat"],
  site_chat: ["chat", "site_chat"],
  department_chat: ["chat", "department_chat"],
  notifications: ["notifications"],
  feedback: ["feedback"],
  reports: ["reports"],
  checklist_report: ["reports", "checklist_report"],
  checklist_task_report: ["reports", "checklist_task_report"],
  workflow: ["workflow"],
  workflow_mapping: ["workflow", "workflow_mapping"],
  approval_hierarchy: ["workflow", "approval_hierarchy"],
  settings_masters: ["settings_masters"],
};

const normalizeModuleKey = (value) => String(value || "").trim().toLowerCase();

const getModuleDependencies = (moduleKey) => {
  const normalizedKey = normalizeModuleKey(moduleKey);
  return MODULE_DEPENDENCIES[normalizedKey] || [normalizedKey];
};

const isModuleEnabled = (moduleKey, flags = STATIC_MODULE_FLAGS) =>
  getModuleDependencies(moduleKey).every((dependencyKey) => flags[dependencyKey] !== false);

module.exports = {
  MODULE_DEPENDENCIES,
  MODULE_SETTINGS_CATALOG,
  MODULE_FLAGS: STATIC_MODULE_FLAGS,
  STATIC_MODULE_FLAGS,
  getModuleDependencies,
  isModuleEnabled,
  normalizeModuleKey,
};
