const ACTION_KEYS = [
  "view",
  "add",
  "edit",
  "delete",
  "approve",
  "reject",
  "status_update",
  "transfer",
  "export",
  "report_view",
];

const ACTION_FIELD_MAP = {
  view: "canView",
  add: "canAdd",
  edit: "canEdit",
  delete: "canDelete",
  approve: "canApprove",
  reject: "canReject",
  status_update: "canStatusUpdate",
  transfer: "canTransfer",
  export: "canExport",
  report_view: "canReportView",
};

const ACTION_LABELS = {
  view: "View",
  add: "Add",
  edit: "Edit",
  delete: "Delete",
  approve: "Approve",
  reject: "Reject",
  status_update: "Status Update",
  transfer: "Transfer",
  export: "Export",
  report_view: "Report View",
};

const MODULE_CATALOG = [
  {
    key: "dashboard",
    name: "Dashboard",
    description: "Role-based landing dashboard and workspace shortcuts.",
    category: "Dashboard",
    routePath: "/dashboard",
    order: 10,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: false,
  },
  {
    key: "dashboard_analytics",
    name: "Dashboard Analytics",
    description: "Detailed score dashboards and drilldowns.",
    category: "Dashboard",
    routePath: "/dashboard-1",
    order: 20,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "employee_master",
    name: "Employee Master",
    description: "Employee directory, profile, onboarding, and activation controls.",
    category: "Masters",
    routePath: "/employees",
    order: 30,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "own_profile",
    name: "Own Profile",
    description: "Current employee profile and mapping details.",
    category: "Workspace",
    routePath: "/me",
    order: 40,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "company_master",
    name: "Company Master",
    description: "Company and director master data.",
    category: "Masters",
    routePath: "/masters/companies",
    order: 50,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "site_master",
    name: "Site Master",
    description: "Site and sub-site master data.",
    category: "Masters",
    routePath: "/masters/sites",
    order: 60,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "main_location",
    name: "Main Location",
    description: "Site-based multi-level location hierarchy.",
    category: "Masters",
    routePath: "/masters/main-locations",
    order: 65,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "material_master",
    name: "Material Master",
    description: "Construction and project material master with UOM, rate, and stock setup.",
    category: "Masters",
    routePath: "/masters/materials",
    order: 66,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "nature_of_work",
    name: "Nature of Work",
    description: "Multi-level work hierarchy with UOM-based outturn calculation.",
    category: "Masters",
    routePath: "/masters/nature-of-work",
    order: 67,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "uom",
    name: "UOM Master",
    description: "Unit of measurement defaults, custom UOMs, and formula mapping.",
    category: "Masters",
    routePath: null,
    order: 68,
    isNavigable: false,
    showInNavbar: false,
    showOnDashboard: false,
  },
  {
    key: "department_master",
    name: "Department Master",
    description: "Department and leadership mapping.",
    category: "Masters",
    routePath: "/masters/departments",
    order: 70,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "sub_department_master",
    name: "Sub Department Master",
    description: "Nested sub-department master setup.",
    category: "Masters",
    routePath: null,
    order: 80,
    isNavigable: false,
    showInNavbar: false,
    showOnDashboard: false,
  },
  {
    key: "designation_master",
    name: "Designation Master",
    description: "Designation and role title master setup.",
    category: "Masters",
    routePath: "/masters/designations",
    order: 90,
    isNavigable: true,
    showInNavbar: false,
    showOnDashboard: true,
  },
  {
    key: "checklist_master",
    name: "Checklist Master",
    description: "Checklist definitions, schedule setup, and admin approval requests.",
    category: "Checklist",
    routePath: "/checklists",
    order: 100,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "assigned_checklists",
    name: "Assigned Checklist",
    description: "Employee checklist tasks assigned to the current user.",
    category: "Checklist",
    routePath: "/checklists",
    order: 110,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "overview_1",
    name: "Overview 1",
    description: "Company and site overview dashboard.",
    category: "Dashboard",
    routePath: "/dashboard-1",
    order: 21,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: false,
  },
  {
    key: "overview_2",
    name: "Overview 2",
    description: "Workflow hierarchy overview dashboard.",
    category: "Dashboard",
    routePath: "/dashboard-2",
    order: 22,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: false,
  },
  {
    key: "dashboard_summary",
    name: "Summary",
    description: "Dashboard marks summary screen.",
    category: "Dashboard",
    routePath: "/dashboard-summary",
    order: 23,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: false,
  },
  {
    key: "tasks",
    name: "Tasks",
    description: "Checklist task administration and task list views.",
    category: "Checklist",
    routePath: "/checklists/tasks",
    order: 111,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "your_checklist",
    name: "Your Checklist",
    description: "Personal checklist workspace for assigned checklist activity.",
    category: "Checklist",
    routePath: "/your-checklist",
    order: 112,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "checklist_transfer",
    name: "Checklist Transfer",
    description: "Temporary and permanent checklist reassignment tools.",
    category: "Checklist",
    routePath: "/masters/checklist-transfer",
    order: 120,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "poll_master",
    name: "Polling System",
    description: "Create scoped polls, manage assignments, and review results.",
    category: "Polling",
    routePath: "/polls",
    order: 125,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "assigned_polls",
    name: "Assigned Polls",
    description: "Employee poll inbox for assigned responses and submissions.",
    category: "Polling",
    routePath: "/polls",
    order: 126,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "poll_results",
    name: "Poll Results",
    description: "Aggregated poll result view.",
    category: "Polling",
    routePath: "/reports/polls",
    order: 127,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "poll_report",
    name: "Poll Report",
    description: "Poll reporting and export access.",
    category: "Polling",
    routePath: "/reports/polls",
    order: 128,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: false,
  },
  {
    key: "workflow_mapping",
    name: "Workflow Mapping",
    description: "Workflow mapping shell for future approval-flow management.",
    category: "Workflow",
    routePath: "/workflow-mapping",
    order: 130,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "approval_hierarchy",
    name: "Approval Hierarchy",
    description: "Approval hierarchy shell for role-specific approval routing.",
    category: "Workflow",
    routePath: "/approval-hierarchy",
    order: 140,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "own_task",
    name: "Own Task",
    description: "Personal reminder and shareable task workspace.",
    category: "Workspace",
    routePath: "/own-tasks",
    order: 150,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "shared_task",
    name: "Shared Task",
    description: "Shared task shell for future dedicated collaboration views.",
    category: "Workspace",
    routePath: "/shared-tasks",
    order: 160,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "approval_inbox",
    name: "Approval Inbox",
    description: "Pending approvals and checklist action inbox.",
    category: "Workspace",
    routePath: "/checklists/approvals",
    order: 170,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "complaints",
    name: "Complaints",
    description: "Employee complaint submission, level-based handling, and status tracking.",
    category: "Workspace",
    routePath: "/complaints",
    order: 172,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "complaint_dashboard",
    name: "Complaint Dashboard",
    description: "Complaint dashboard cards and handling queue.",
    category: "Workspace",
    routePath: "/complaints",
    order: 173,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "complaint_report",
    name: "Complaint Report",
    description: "Complaint report filters, drilldowns, and exports.",
    category: "Analytics",
    routePath: "/complaints/reports",
    order: 174,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "employee_attendance",
    name: "Employee Attendance",
    description: "Attendance dashboard, daily entry, and self check-in/check-out.",
    category: "Attendance",
    routePath: "/attendance",
    order: 175,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "attendance_reports",
    name: "Attendance Reports",
    description: "Monthly attendance summaries, filters, and exports.",
    category: "Attendance",
    routePath: "/attendance/reports",
    order: 176,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "attendance_regularization",
    name: "Attendance Regularization",
    description: "Attendance correction requests and approval flow.",
    category: "Attendance",
    routePath: "/attendance/regularization",
    order: 177,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "attendance_settings",
    name: "Attendance Settings",
    description: "Shift timing, grace period, and self-service attendance rules.",
    category: "Attendance",
    routePath: "/attendance/settings",
    order: 178,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "reports",
    name: "Reports",
    description: "Checklist reports and exports.",
    category: "Analytics",
    routePath: "/reports/checklists",
    order: 180,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "checklist_report",
    name: "Checklist Report",
    description: "Checklist report filters and exports.",
    category: "Analytics",
    routePath: "/reports/checklists",
    order: 181,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "checklist_task_report",
    name: "Checklist Task Report",
    description: "Checklist task report and task-level mark split-up.",
    category: "Analytics",
    routePath: "/reports/checklists",
    order: 182,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: false,
  },
  {
    key: "notifications",
    name: "Notifications",
    description: "Notification center shell and alert permissions.",
    category: "Communication",
    routePath: "/notifications",
    order: 190,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "feedback",
    name: "Feedback",
    description: "Employee feedback notifications and review access.",
    category: "Communication",
    routePath: null,
    order: 195,
    isNavigable: false,
    showInNavbar: false,
    showOnDashboard: false,
  },
  {
    key: "site_chat",
    name: "Site Chat",
    description: "Site-wide conversation channel.",
    category: "Communication",
    routePath: "/chat",
    order: 200,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "department_chat",
    name: "Department Chat",
    description: "Department-level chat channel.",
    category: "Communication",
    routePath: "/department-chat",
    order: 210,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "user_management",
    name: "User Management",
    description: "Login-user creation, editing, and deletion.",
    category: "Administration",
    routePath: "/users",
    order: 220,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "role_permission_setup",
    name: "Role Permission Setup",
    description: "Role matrix, overrides, and mapping administration.",
    category: "Administration",
    routePath: "/permissions/roles",
    order: 230,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "module_settings",
    name: "Module Settings",
    description: "Enable and disable completed modules without removing code or data.",
    category: "Administration",
    routePath: "/module-settings",
    order: 235,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "admin_approvals",
    name: "Admin Approvals",
    description: "Checklist master admin approval queue.",
    category: "Administration",
    routePath: "/checklists/admin-approvals",
    order: 236,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
  {
    key: "settings_masters",
    name: "Settings / Masters",
    description: "General settings and master configuration shell.",
    category: "Administration",
    routePath: "/settings",
    order: 240,
    isNavigable: true,
    showInNavbar: true,
    showOnDashboard: true,
  },
];

const buildAllDeniedPermissions = () =>
  Object.values(ACTION_FIELD_MAP).reduce((result, fieldKey) => {
    result[fieldKey] = false;
    return result;
  }, {});

const grant = (...actionKeys) => {
  const permissions = buildAllDeniedPermissions();
  actionKeys.forEach((actionKey) => {
    const fieldKey = ACTION_FIELD_MAP[actionKey];
    if (fieldKey) {
      permissions[fieldKey] = true;
    }
  });
  return permissions;
};

const grantAll = () =>
  Object.values(ACTION_FIELD_MAP).reduce((result, fieldKey) => {
    result[fieldKey] = true;
    return result;
  }, {});

const SYSTEM_ROLES = [
  {
    key: "main_admin",
    name: "Main Admin",
    description: "Full access to every module, action, report, and master screen.",
    isSystem: true,
    dashboardType: "admin",
    scopeStrategy: "all",
    homeModuleKey: "dashboard",
    defaultPermissions: MODULE_CATALOG.reduce((result, moduleItem) => {
      result[moduleItem.key] = grantAll();
      return result;
    }, {}),
  },
  {
    key: "checklist_master_user",
    name: "Checklist Master User",
    description: "Checklist-focused access with request-based edits and transfers.",
    isSystem: true,
    dashboardType: "site",
    scopeStrategy: "mapped",
    homeModuleKey: "checklist_master",
    defaultPermissions: {
      dashboard: grant("view"),
      overview_1: grant("view", "report_view"),
      overview_2: grant("view", "report_view"),
      dashboard_summary: grant("view", "report_view"),
      checklist_master: grant("view", "add", "edit", "transfer", "export"),
      tasks: grant("view"),
      checklist_transfer: grant("view", "transfer"),
      poll_master: grant("view", "add", "edit", "delete", "status_update", "report_view"),
      poll_results: grant("view", "report_view"),
      poll_report: grant("view", "report_view", "export"),
      workflow_mapping: grant("view"),
      approval_hierarchy: grant("view"),
      role_permission_setup: grant("view"),
    },
  },
  {
    key: "site_user",
    name: "Site User",
    description: "Site-scoped dashboard, approvals, reports, chat, and assigned data.",
    isSystem: true,
    dashboardType: "site",
    scopeStrategy: "mapped",
    homeModuleKey: "dashboard",
    defaultPermissions: {
      dashboard: grant("view"),
      dashboard_analytics: grant("view", "report_view"),
      overview_1: grant("view", "report_view"),
      overview_2: grant("view", "report_view"),
      dashboard_summary: grant("view", "report_view"),
      assigned_checklists: grant("view"),
      tasks: grant("view"),
      your_checklist: grant("view"),
      poll_master: grant("view", "add", "edit", "report_view"),
      poll_results: grant("view", "report_view"),
      approval_inbox: grant("view", "approve", "reject"),
      complaints: grant("view"),
      complaint_dashboard: grant("view"),
      complaint_report: grant("view", "report_view", "export"),
      employee_attendance: grant("view"),
      attendance_reports: grant("view", "report_view", "export"),
      attendance_regularization: grant("view", "approve", "reject"),
      reports: grant("view", "report_view", "export"),
      checklist_report: grant("view", "report_view", "export"),
      notifications: grant("view"),
      site_chat: grant("view", "add"),
      own_profile: grant("view"),
    },
  },
  {
    key: "department_user",
    name: "Department User",
    description: "Department-scoped dashboard, approvals, reports, and collaboration.",
    isSystem: true,
    dashboardType: "department",
    scopeStrategy: "mapped",
    homeModuleKey: "dashboard",
    defaultPermissions: {
      dashboard: grant("view"),
      dashboard_analytics: grant("view", "report_view"),
      overview_1: grant("view", "report_view"),
      overview_2: grant("view", "report_view"),
      dashboard_summary: grant("view", "report_view"),
      assigned_checklists: grant("view"),
      tasks: grant("view"),
      your_checklist: grant("view"),
      poll_master: grant("view", "add", "edit", "report_view"),
      poll_results: grant("view", "report_view"),
      approval_inbox: grant("view", "approve", "reject"),
      complaints: grant("view"),
      complaint_dashboard: grant("view"),
      complaint_report: grant("view", "report_view", "export"),
      employee_attendance: grant("view"),
      attendance_reports: grant("view", "report_view", "export"),
      attendance_regularization: grant("view", "approve", "reject"),
      reports: grant("view", "report_view", "export"),
      checklist_report: grant("view", "report_view", "export"),
      notifications: grant("view"),
      department_chat: grant("view", "add"),
      own_profile: grant("view"),
    },
  },
  {
    key: "employee",
    name: "Employee",
    description: "Own profile, assigned checklist, own tasks, and notifications.",
    isSystem: true,
    dashboardType: "employee",
    scopeStrategy: "own",
    homeModuleKey: "dashboard",
    defaultPermissions: {
      dashboard: grant("view"),
      dashboard_summary: grant("view"),
      assigned_checklists: grant("view", "edit"),
      your_checklist: grant("view"),
      assigned_polls: grant("view", "edit"),
      complaints: grant("view", "add"),
      complaint_dashboard: grant("view", "add"),
      employee_attendance: grant("view", "add", "edit"),
      attendance_regularization: grant("view", "add"),
      own_task: grant("view", "add", "edit"),
      reports: grant("view", "report_view"),
      checklist_report: grant("view", "report_view"),
      notifications: grant("view"),
      own_profile: grant("view"),
    },
  },
  {
    key: "superior_head",
    name: "Superior / Head",
    description: "Managed-team dashboard, approval inbox, reports, and employee oversight.",
    isSystem: true,
    dashboardType: "superior",
    scopeStrategy: "managed",
    homeModuleKey: "dashboard",
    defaultPermissions: {
      dashboard: grant("view"),
      dashboard_analytics: grant("view", "report_view"),
      overview_1: grant("view", "report_view"),
      overview_2: grant("view", "report_view"),
      dashboard_summary: grant("view", "report_view"),
      assigned_checklists: grant("view"),
      tasks: grant("view"),
      your_checklist: grant("view"),
      poll_master: grant("view", "add", "edit", "report_view"),
      poll_results: grant("view", "report_view"),
      approval_inbox: grant("view", "approve", "reject"),
      complaints: grant("view", "add"),
      complaint_dashboard: grant("view", "add"),
      complaint_report: grant("view", "report_view", "export"),
      employee_attendance: grant("view"),
      attendance_reports: grant("view", "report_view", "export"),
      attendance_regularization: grant("view", "approve", "reject"),
      reports: grant("view", "report_view", "export"),
      checklist_report: grant("view", "report_view", "export"),
      employee_master: grant("view"),
      notifications: grant("view"),
      own_profile: grant("view"),
      own_task: grant("view", "add", "edit"),
      site_chat: grant("view", "add"),
      department_chat: grant("view", "add"),
    },
  },
];

module.exports = {
  ACTION_KEYS,
  ACTION_FIELD_MAP,
  ACTION_LABELS,
  MODULE_CATALOG,
  SYSTEM_ROLES,
  buildAllDeniedPermissions,
  grant,
  grantAll,
};
